definitions:
  models.Todo:
    properties:
      _id:
        type: string
      completed:
        type: boolean
      item:
        type: string
    type: object
  services.UpdateTodoDto:
    properties:
      completed:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /todos:
    get:
      description: Retrieves all todo items from te db.
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Todo'
            type: array
      summary: Get all todos
      tags:
      - todos
    post:
      consumes:
      - application/json
      description: Create a new todo item
      parameters:
      - description: Todo Item
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/models.Todo'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Todo'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Add a new Todo
      tags:
      - todos
  /todos/{id}:
    get:
      description: Retrieves a todo item by its unique identifier.
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Todo'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Not found
          schema:
            type: string
      summary: Get a Todo by ID
      tags:
      - todos
    patch:
      consumes:
      - application/json
      description: Update a todo by it's id
      parameters:
      - description: Is completed
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/services.UpdateTodoDto'
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Todo'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Update todo
      tags:
      - todos
swagger: "2.0"
